mybatis:
  type-aliases-package: com.joy.flash.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/joy/flash/dao/*.xml

#  type-handlers-package: com.joy.

spring:
  application:
    name: flash-sale
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flash_sale?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    filters: log4j,wall,mergeStat
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 4000
#    tomcat:
#      max-wait: 60000
  resources:
    add-mappings: true
#    cache-period: 3600
    chain:
      cache: true
      enabled: true
#      gzipped: true
      html-application-cache: true
    static-locations: classpath:/static/

  rabbitmq:
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
    listener:
      simple:
        concurrency: 10 # 消费者的并发数量
        max-concurrency: 10
        prefetch: 1 # 每次从队列里取几个
        auto-startup: true
        default-requeue-rejected: true


redis:
  host: 127.0.0.1
  port: 6379
  timeout: 10
#  password: ""
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500

# rabbitmq



# redis

# mybatis