mybatis:
  type-aliases-package: com.joy.flash.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/joy/flash/dao/*.xml

#  type-handlers-package: com.joy.

spring:
  application:
    name: flash-sale
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flash_sale?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    filters: log4j,wall,mergeStat
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 4000
    tomcat:
      max-wait: 60000

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 10
#  password: ""
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500


# redis

# mybatis